[package]
name = "skin-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ears-rs = { git = "https://github.com/NickAcPT/ears-rs" }
console_error_panic_hook = "*"
wasm-bindgen = { workspace = true }
nmsr-rasterizer-test = { path = "../../../nmsr-rasterizer-test" }
nmsr-player-parts = { git = "https://github.com/NickAcPT/nmsr-rs" }
# web-sys has to be locked to 0.3.64 because otherwise, wgpu breaks
web-sys = { version = "=0.3.64", features = ["HtmlCanvasElement", "CanvasRenderingContext2d", "ImageData"] }
winit = "0.28.6"
glam = { version = "*", features = ["core-simd"] }
js-utils = { workspace = true }
wasm-bindgen-futures = "0.4.38"
send_wrapper = "0.6.0"
image = { version = "0", default-features = false, features = ["png"] }

[features]
default = ["ears"]
ears = ["nmsr-player-parts/ears"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "--enable-simd",
    "-g",
    "-O3",
]
