[package]
name = "skin-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ears-rs = { git = "https://github.com/NickAcPT/ears-rs" }
console_error_panic_hook = "*"
wasm-bindgen = { workspace = true }
nmsr-rendering = { path = "../../../nmsr-rs/nmsr-3d-renderer/nmsr-rendering" }
nmsr-player-parts = { path = "../../../nmsr-rs/nmsr-3d-renderer/nmsr-player-parts" }
# web-sys has to be locked to 0.3.64 because otherwise, wgpu breaks
web-sys = { version = "=0.3.64", features = ["HtmlCanvasElement"] }
# We're being spicy here by asking it to be send and sync..
wgpu = { version = "*", features = ["fragile-send-sync-non-atomic-wasm"] }
winit = "0.28.6"
js-utils = { workspace = true }
wasm-bindgen-futures = "0.4.38"
send_wrapper = "0.6.0"
image = { version = "0", default-features = false, features = ["png"] }

[features]
default = ["ears"]
ears = ["nmsr-rendering/ears", "nmsr-player-parts/ears"]
